version: "3"
services:
  apiserver:
    image: littlefishtentears/cngalwebsiteapiserver:latest
    container_name: apiserver
    environment:
      - TZ=${TZ}
      - CnGalDBConnection=${CnGalDBConnection}
      - Password=${Password}
      - WeiboAppKey=${WeiboAppKey}
      - AppSecret=${AppSecret}
      - ThirdPartyLoginQQ_client_id=${ThirdPartyLoginQQ_client_id}
      - ThirdPartyLoginQQ_client_secret=${ThirdPartyLoginQQ_client_secret}
      - TypesenseAPIKey=${TypesenseAPIKey}
      - AccessKeyId=${AccessKeyId}
      - AccessKeySecret=${AccessKeySecret}
      - SliotsImageAPIToken=${SliotsImageAPIToken}
      - SteamAPIToken=${SteamAPIToken}
      - IsthereanydealAPIToken=${IsthereanydealAPIToken}
      - GEETEST_ID=${GEETEST_ID}
      - GEETEST_KEY=${GEETEST_KEY}
      - JwtSecurityKey=${JwtSecurityKey}
      - WeiXinToken=${WeiXinToken}
      - WeiXinEncodingAESKey=${WeiXinEncodingAESKey}
      - WeixinAppId=${WeixinAppId}
      - WeiXinAppSecret=${WeiXinAppSecret}
      - TucangCCAPIToken=${TucangCCAPIToken}
      - BilibiliCookie=${BilibiliCookie}
      # Ids 地址
      - Authority=${Authority}
      # 图床API
      - ImageApiPath=${ImageApiPath}
      # IP 白名单
      - IpWhitelist=${IpWhitelist}
      # 事件总线
      - EventBus_HostName=${EventBus_HostName}
      - EventBus_Port=${EventBus_Port}
      - EventBus_UserName=${EventBus_UserName}
      - EventBus_Password=${EventBus_Password}
    hostname: apiserver
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1.2G
    ports:
      - "3001:8081"
      - "2001:8080"
