import os
import pathlib
import re
import urllib.request
from concurrent.futures import ThreadPoolExecutor

MDI_VERSION = "7.4.47"
MDI_URL = f"https://cdn.jsdelivr.net/npm/@mdi/js@{MDI_VERSION}/mdi.js"
EXPORT_RE = re.compile(r'var (mdi[A-Za-z0-9]+) = "([^"]+)";')
ICON_TOKEN_RE = re.compile(r"\bmdi[A-Za-z0-9]+\b")


def parse_exports(js: str) -> dict[str, str]:
    return {match.group(1): match.group(2) for match in EXPORT_RE.finditer(js)}


def load_mdi_js(repo_root: pathlib.Path) -> str:
    cache_dir = repo_root / ".cache"
    cache_file = cache_dir / f"mdi-{MDI_VERSION}.js"
    if cache_file.exists():
        return cache_file.read_text(encoding="utf-8")

    cache_dir.mkdir(exist_ok=True)
    with urllib.request.urlopen(MDI_URL, timeout=30) as response:
        js = response.read().decode("utf-8")
    cache_file.write_text(js, encoding="utf-8")
    return js


def extract_icon_names_from_file(path: pathlib.Path) -> set[str]:
    text = path.read_text(encoding="utf-8")
    return set(ICON_TOKEN_RE.findall(text))


def collect_icon_names(shared_root: pathlib.Path, main_site_root: pathlib.Path) -> list[str]:
    icon_names: set[str] = set()
    razor_files = [*shared_root.rglob("*.razor"), *main_site_root.rglob("*.razor")]

    # File reading is IO bound, so thread-based parallelism improves throughput.
    max_workers = min(32, max(4, (os.cpu_count() or 1) * 4))
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        for names in executor.map(extract_icon_names_from_file, razor_files, chunksize=16):
            icon_names.update(names)

    return sorted(icon_names)


def build_output(entries: list[tuple[str, str]]) -> str:
    lines: list[str] = [
        "// <auto-generated />",
        "// Generated by mdi_extract.py.",
        f"// Source: @mdi/js v{MDI_VERSION}",
        "",
        "#nullable enable",
        "",
        "namespace CnGalWebSite.MainSite.Shared.Components.DesignSystem.Components;",
        "",
        "internal static partial class CgMdiIconMap",
        "{",
        "    private static readonly IReadOnlyDictionary<string, string> Paths = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)",
        "    {",
    ]

    for mdi_symbol, path_data in sorted(entries, key=lambda x: x[0]):
        lines.append(f'        ["{mdi_symbol}"] = "{path_data}",')

    lines.extend(
        [
            "    };",
            "",
            "    public static bool TryGetPath(string? iconName, out string path)",
            "    {",
            "        if (string.IsNullOrWhiteSpace(iconName))",
            "        {",
            "            path = string.Empty;",
            "            return false;",
            "        }",
            "",
            "        return Paths.TryGetValue(iconName, out path!);",
            "    }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    repo_root = pathlib.Path(__file__).resolve().parent
    output_file = (
        repo_root
        / "CnGalWebSite"
        / "CnGalWebSite.MainSite.Shared"
        / "Components"
        / "DesignSystem"
        / "CgMdiIconMap.g.cs"
    )

    js = load_mdi_js(repo_root)
    exports = parse_exports(js)
    discovered_icons = collect_icon_names(
        repo_root / "CnGalWebSite" / "CnGalWebSite.MainSite.Shared",
        repo_root / "CnGalWebSite" / "CnGalWebSite.MainSite",
    )

    entries: list[tuple[str, str]] = []
    unresolved: list[str] = []
    for mdi_symbol in discovered_icons:
        path_data = exports.get(mdi_symbol)
        if path_data is None:
            unresolved.append(mdi_symbol)
            continue
        entries.append((mdi_symbol, path_data))

    if unresolved:
        print(f"skipped non-icon or unresolved names: {', '.join(unresolved)}")

    output = build_output(entries)
    if output_file.exists() and output_file.read_text(encoding="utf-8") == output:
        print(f"unchanged: {output_file}")
    else:
        output_file.write_text(output, encoding="utf-8")
        print(f"generated: {output_file}")
    print(f"discovered tokens: {len(discovered_icons)}")
    print(f"icons: {len(entries)}")


if __name__ == "__main__":
    main()
