import datetime
import pathlib
import re
import urllib.request

MDI_VERSION = "7.4.47"
MDI_URL = f"https://cdn.jsdelivr.net/npm/@mdi/js@{MDI_VERSION}/mdi.js"


def parse_exports(js: str) -> dict[str, str]:
    result: dict[str, str] = {}
    for match in re.finditer(r'var (mdi[A-Za-z0-9]+) = "([^"]+)";', js):
        result[match.group(1)] = match.group(2)
    return result


def collect_icon_names(shared_root: pathlib.Path, main_site_root: pathlib.Path) -> list[str]:
    icon_names: set[str] = set()

    def collect_from_text(text: str) -> None:
        for match in re.findall(r"\bmdi[A-Za-z0-9]+\b", text):
            icon_names.add(match)

    for razor_file in shared_root.rglob("*.razor"):
        collect_from_text(razor_file.read_text(encoding="utf-8"))

    # Some icon names can live outside Shared in host page/layout.
    for razor_file in main_site_root.rglob("*.razor"):
        collect_from_text(razor_file.read_text(encoding="utf-8"))

    return sorted(icon_names)


def build_output(entries: list[tuple[str, str, str]]) -> str:
    timestamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")
    lines: list[str] = [
        "// <auto-generated />",
        f"// Generated by mdi_extract.py at {timestamp}.",
        f"// Source: @mdi/js v{MDI_VERSION}",
        "",
        "#nullable enable",
        "",
        "namespace CnGalWebSite.MainSite.Shared.Components.DesignSystem.Components;",
        "",
        "internal static partial class CgMdiIconMap",
        "{",
        "    private static readonly IReadOnlyDictionary<string, string> Paths = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)",
        "    {",
    ]

    for mdi_symbol, path_data in sorted(entries, key=lambda x: x[0]):
        lines.append(f'        ["{mdi_symbol}"] = "{path_data}",')

    lines.extend(
        [
            "    };",
            "",
            "    public static bool TryGetPath(string? iconName, out string path)",
            "    {",
            "        if (string.IsNullOrWhiteSpace(iconName))",
            "        {",
            "            path = string.Empty;",
            "            return false;",
            "        }",
            "",
            "        return Paths.TryGetValue(iconName, out path!);",
            "    }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    repo_root = pathlib.Path(__file__).resolve().parent
    output_file = (
        repo_root
        / "CnGalWebSite"
        / "CnGalWebSite.MainSite.Shared"
        / "Components"
        / "DesignSystem"
        / "Components"
        / "CgMdiIconMap.g.cs"
    )

    js = urllib.request.urlopen(MDI_URL).read().decode("utf-8")
    exports = parse_exports(js)
    discovered_icons = collect_icon_names(
        repo_root / "CnGalWebSite" / "CnGalWebSite.MainSite.Shared",
        repo_root / "CnGalWebSite" / "CnGalWebSite.MainSite",
    )

    entries: list[tuple[str, str]] = []
    unresolved: list[str] = []
    for mdi_symbol in discovered_icons:
        path_data = exports.get(mdi_symbol)
        if path_data is None:
            unresolved.append(mdi_symbol)
            continue
        entries.append((mdi_symbol, path_data))

    if unresolved:
        print(f"skipped non-icon or unresolved names: {', '.join(unresolved)}")

    output_file.write_text(build_output(entries), encoding="utf-8")
    print(f"generated: {output_file}")
    print(f"discovered tokens: {len(discovered_icons)}")
    print(f"icons: {len(entries)}")


if __name__ == "__main__":
    main()
