version: "3"
services:
  blazorserver:
    image: littlefishtentears/cngalwebsiteserver:latest
    container_name: blazorserver
    environment:
      - TZ=${TZ}
      - WebApiPath=${WebApiPath}
      - Authority=${Authority}
      - ClientId=${ClientId}
      - ClientSecret=${ClientSecret}
      # 管理令牌储存
      - TokenAPI=${TokenAPI}
      - TokenAPISecret=${TokenAPISecret}
      # 图床API
      - ImageApiPath=${ImageApiPath}
      # Live2D
      - Live2D_DataUrl=${Live2D_DataUrl}
      - Live2D_ResourcesPath=${Live2D_ResourcesPath}
      # 定时任务API
      - TaskApiPath=${TaskApiPath}
    hostname: blazorserver
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: ${resources_limits_memory}
    ports:
      - "3002:8081"
      - "2002:8080"