services:
  blazorserver:
    image: littlefishtentears/cngalwebsiteserver:${IMAGE_TAG:-latest}
    container_name: blazorserver
    environment:
      - TZ=${TZ:-Asia/Shanghai}
      - WebApiPath=${WebApiPath:-https://api.cngal.org/}
      - Authority=${Authority:-https://oauth2.cngal.org}
      - ClientId=${ClientId}
      - ClientSecret=${ClientSecret}
      # 管理令牌储存
      - TokenAPI=${TokenAPI:-https://oauth2.cngal.org/api/tokens/}
      - TokenAPISecret=${TokenAPISecret}
      # 图床API
      - ImageApiPath=${ImageApiPath:-https://api.cngal.top/}
      # Live2D
      - Live2D_DataUrl=${Live2D_DataUrl}
      - Live2D_ResourcesPath=${Live2D_ResourcesPath}
      # 定时任务API
      - TaskApiPath=${TaskApiPath}
    hostname: blazorserver
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: ${RESOURCES_LIMITS_MEMORY:-1.5G}
    ports:
      - "2002:8080"
      # - "3002:8081"
    volumes:
      - blazorserver-DataProtection-Keys:/home/app/.aspnet/DataProtection-Keys
    labels:
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE:-true} # watchtower
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: 10
    networks:
      - web

volumes:
  blazorserver-DataProtection-Keys:

networks:
  web:
    external: true
