services:
  robotclientx:
    image: littlefishtentears/cngalwebsiterobotclientx:latest
    container_name: robotclientx
    environment:
      - TZ=${TZ}
      # 账号
      - QQ=${QQ}
      # 称呼
      - RobotName=${RobotName}
      # 接收预警的QQ群
      - WarningQQGroup=${WarningQQGroup}
      # Mirai Url
      - MiraiUrl=${MiraiUrl}
      # Mirai 验证密匙
      - NormalVerifyKey=${NormalVerifyKey}
      # QQ频道 AppId
      - ChannelAppId=${ChannelAppId}
      # QQ频道 Token
      - ChannelToken=${ChannelToken}
      # QQ频道 AppKey
      - ChannelAppKey=${ChannelAppKey}
      # CnGal资料站 API
      - WebApiPath=${WebApiPath}
      # 网站名称
      - WebSiteName=${WebSiteName}
      # 网站背景图
      - WebSiteImage=${WebSiteImage}
      # 网站主题颜色
      - WebSiteTheme=${WebSiteTheme}
      # 事件总线
      - EventBus_HostName=${EventBus_HostName}
      - EventBus_Port=${EventBus_Port}
      - EventBus_UserName=${EventBus_UserName}
      - EventBus_Password=${EventBus_Password}
      # 群聊历史记录最大条数
      - GroupHistoryMax=${GroupHistoryMax}
      # 群聊历史记录达到最大条数后，保留最近N条消息
      - GroupHistoryMin=${GroupHistoryMin}
    hostname: robotclientx
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: ${resources_limits_memory}
    ports:
      - "2004:8080"
    volumes:
      - ${MNT_DIR}/robotclientx/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
      - ${MNT_DIR}/robotclientx/Data:/app/wwwroot/Data
