services:
  expo:
    image: littlefishtentears/cngalwebsiteexpo:${IMAGE_TAG:-latest}
    container_name: expo
    environment:
      - TZ=${TZ:-Asia/Shanghai}
      - WebApiPath=${WebApiPath:-https://api.cngal.org/}
      - Authority=${Authority:-https://oauth2.cngal.org}
      - ClientId=${ClientId}
      - ClientSecret=${ClientSecret}
      # 图床API
      - ImageApiPath=${ImageApiPath}
    hostname: expo
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: ${RESOURCES_LIMITS_MEMORY:-1.5G}
    ports:
      - "2202:8080"
      # - "3302:8081"
    volumes:
      - expo-DataProtection-Keys:/home/app/.aspnet/DataProtection-Keys
    labels:
      # watchtower
      - com.centurylinklabs.watchtower.enable=${WATCHTOWER_ENABLE:-true}
    networks:
      - web
volumes:
  expo-DataProtection-Keys:
networks:
  web:
    external: true
