services:
  examineservice:
    image: ghcr.io/cngal/cngalwebsite-examineservice:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME:-examineservice}
    hostname: examineservice

    restart: unless-stopped

    env_file:
      - path: .env
        required: false
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      # 事件总线 主机名称
      EventBus_HostName: ${EventBus_HostName}
      # 事件总线 端口
      EventBus_Port: ${EventBus_Port:-5672}
      # 事件总线 用户名
      EventBus_UserName: ${EventBus_UserName}
      # 事件总线 密码
      EventBus_Password: ${EventBus_Password}

    labels:
      com.centurylinklabs.watchtower.enable: ${WATCHTOWER_ENABLE:-true}

    volumes:
      - ${DATA_DIR:?DATA_DIR is required}/SensitiveWords:/app/Data/SensitiveWords:ro

    deploy:
      resources:
        limits:
          memory: ${RESOURCES_LIMITS_MEMORY:-${resources_limits_memory:-100m}}
