services:
  apiserver:
    image: littlefishtentears/cngalwebsiteexamineservice:${IMAGE_TAG:-latest}
    container_name: examineservice
    hostname: examineservice
    restart: unless-stopped

    environment:
      TZ: ${TZ:-Asia/Shanghai}
      # 事件总线 主机名称
      EventBus_HostName: ${EventBus_HostName}
      # 事件总线 端口
      EventBus_Port: ${EventBus_Port:-5672}
      # 事件总线 用户名
      EventBus_UserName: ${EventBus_UserName}
      # 事件总线 密码
      EventBus_Password: ${EventBus_Password}

    labels:
      com.centurylinklabs.watchtower.enable: ${WATCHTOWER_ENABLE:-true}

    volumes:
      - ${DATA_DIR}/SensitiveWords:/app/Data/SensitiveWords

    deploy:
      resources:
        limits:
          memory: ${resources_limits_memory:-100m}

    networks:
      - web

networks:
  web:
    external: true
