version: "3"
services:
  blazorserver:
    image: littlefishtentears/cngalwebsiteidentityserveradmin:latest
    container_name: identityserveradmin
    environment:
      - TZ=${TZ}
      - Authority=${Authority}
      - ClientId=${ClientId}
      - ClientSecret=${ClientSecret}
      - IdsApiUrl=${IdsApiUrl}
      # 管理令牌储存
      - TokenAPI=${TokenAPI}
      - TokenAPISecret=${TokenAPISecret}
    hostname: identityserveradmin
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 0.7G
    ports:
      - "5100:8080"