version: "3"
services:
  robotclientx:
    image: littlefishtentears/cngalwebsite-project-api:latest
    container_name: project-api
    environment:
      - TZ=${TZ}
      # 数据库连接字符串
      - DefaultDBConnection=${DefaultDBConnection}
      # Ids 地址
      - Authority=${Authority}
      # CnGal
      - CnGalAPI=${CnGalAPI}
      # CnGal接口令牌
      - JwtSecurityKey=${JwtSecurityKey}
      # 事件总线
      - EventBus_HostName=${EventBus_HostName}
      - EventBus_Port=${EventBus_Port}
      - EventBus_UserName=${EventBus_UserName}
      - EventBus_Password=${EventBus_Password}
      # 通知QQ群
      - NoticeQQGroup=${NoticeQQGroup}
    hostname: project-api
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: ${resources_limits_memory}
    ports:
      - "2007:8080"