name: Build and push IdentityServer.Admin
 
on: workflow_dispatch # 手动触发
 
jobs:
  build-and-push:
      if: ${{ github.ref == 'refs/heads/master' && github.repository == 'CnGal/CnGalWebSite' }}  # 检测master分支是否有更新
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@master

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Generate timestamp tag
          id: timestamp
          run: echo "tag=$(date +'%Y%m%d-%H%M')" >> $GITHUB_OUTPUT
               
        - name: build IdentityServer.Admin and push to Dockerhub
          uses: docker/build-push-action@v3
          with:
            context: .
            file: ./CnGalWebSite/CnGalWebSite.IdentityServer.Admin.SSR/Dockerfile # Dockerfile 位置
            #platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
            push: true
            tags: |
              littlefishtentears/cngalwebsiteidentityserveradmin:latest
              littlefishtentears/cngalwebsiteidentityserveradmin:${{ steps.timestamp.outputs.tag }}
        
